import { notFound } from "next/navigation";
import { headers } from "next/headers";
import type { Metadata } from "next";
import { getPublicAscent } from "@/lib/services/public-ascent.service";
import { getRarityId, RARITY_LABELS } from "@/lib/rarity";
import { peakDisplayName } from "@/lib/peak-name";
import { PeakadexLogo } from "@/components/brand/Logo";
import { ShareCard } from "@/components/share/ShareCard";
import type { ElevationProfile as ElevationProfileData } from "@/lib/services/elevation.service";
import { getT, isValidLocale } from "@/lib/i18n";

const APP_URL =
  process.env.APP_URL ?? process.env.NEXTAUTH_URL ?? "https://www.peakadex.com";

async function getBaseUrl(): Promise<string> {
  try {
    const h = await headers();
    const host = h.get("host");
    if (host) return host.includes("localhost") ? `http://${host}` : `https://${host}`;
  } catch {}
  return APP_URL;
}

// ── Metadata ──────────────────────────────────────────────────────────────────

export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ lang?: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const { lang } = await searchParams;
  const locale = isValidLocale(lang ?? "") ? lang! : "es";
  const t = getT(locale);

  const [ascent, baseUrl] = await Promise.all([getPublicAscent(id), getBaseUrl()]);
  if (!ascent) return { title: "Peakadex" };

  const rarity = getRarityId(ascent.peak.altitudeM);
  const rarityLabel = RARITY_LABELS[rarity];

  const title = `${ascent.user.name} ha capturado ${peakDisplayName(ascent.peak)}`;
  const description = `Altitud: ${ascent.peak.altitudeM} m · Rareza: ${rarityLabel}`;

  // Card-style OG image generated by /api/og/[id] (sharp-based, no next/og).
  // Falls back to the raw photo URL if the API is unavailable.
  const ogImage = `${baseUrl}/api/og/${id}`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url: `${baseUrl}/ascent/${id}`,
      siteName: "Peakadex",
      images: [
        {
          url: ogImage,
          width: 1080,
          height: 1350,
          type: "image/jpeg",
          alt: title,
        },
      ],
      type: "article",
    },
    twitter: {
      card: "summary",
      title,
      description,
      images: [ogImage],
    },
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatDate(iso: string, locale: string) {
  return new Date(iso).toLocaleDateString(locale, {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default async function PublicAscentPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ lang?: string }>;
}) {
  const { id } = await params;
  const { lang } = await searchParams;
  const locale = isValidLocale(lang ?? "") ? lang! : "es";
  const t = getT(locale);

  const ascent = await getPublicAscent(id);
  if (!ascent) notFound();

  return (
    <div
      style={{
        minHeight: "100svh",
        background: "#EDEEF0",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        padding: "24px 16px 48px",
        fontFamily: "var(--font-inter, system-ui, sans-serif)",
      }}
    >
      {/* Logo */}
      <div style={{ marginBottom: 24 }}>
        <PeakadexLogo height={32} iconScale={0.9} />
      </div>

      {/* Flippable card — front (photo + stats) / back (map + stats + Cordada) */}
      <ShareCard
        ascentId={ascent.id}
        dateStr={formatDate(ascent.date, t.dateLocale)}
        route={ascent.route}
        description={ascent.description}
        peak={{
          id: ascent.peak.id,
          name: ascent.peak.name,
          nameEn: ascent.peak.nameEn,
          altitudeM: ascent.peak.altitudeM,
          mountainRange: ascent.peak.mountainRange,
          isMythic: ascent.peak.isMythic,
          rarityId: ascent.peak.rarityId,
          latitude: ascent.peak.latitude,
          longitude: ascent.peak.longitude,
          elevationProfile: (ascent.peak.elevationProfile as ElevationProfileData | null) ?? null,
        }}
        photoUrl={ascent.photoUrl}
        ownerName={ascent.user.name}
        ownerAvatarUrl={ascent.user.avatarUrl}
        persons={ascent.persons}
        peakStats={ascent.peakStats}
        isLandscape={ascent.photoCropAspect === "landscape"}
        locale={t.dateLocale}
        registerUrl={`${APP_URL}/register`}
        labels={{
          rarity: t.card_rarity,
          altitude: t.card_altitude,
          reward: t.card_reward,
          mythic: t.card_mythic,
          joinCta: t.share_joinCta,
          cordada: t.card_cordada_label_other,
          tapToFlip: t.share_tapToFlip,
          cairn: "1 Cairn",
        }}
      />

      {/* Footer */}
      <div style={{ marginTop: 24, fontSize: 11, color: "#94A3B8" }}>
        © {new Date().getFullYear()} Peakadex
      </div>
    </div>
  );
}
